version: '3.7'
services:
  web-mkt:
    build:
      context: .
      dockerfile: Dockerfile
    image: marketing:latest
    container_name: web-mkt
    restart: always
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: ./mvnw install -DskipTests
    environment:
#      SERVER_PORT: 8085
      SPRING_RABBITMQ_HOST: rabbitmq-mkt
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USERNAME: admin
#      RABBITMQ_PASSWORD: admin
    ports:
      - 8086:8086
    depends_on:
      - rabbitmq
      - mongo-mkt
  mongo-mkt:
    image: mongo
    container_name: mongo-mkt
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mkt-usuario
      MONGO_INITDB_ROOT_PASSWORD: mkt-senha
      MONGO_INITDB_DATABASE: mkt
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
#    Portas para acesso de protocolos AMQP e Painel do rabbit
    ports:
      - 5672:5672
      - 15672:15672
#    persistencia de dados caso o cotainer morra
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mkt-usuario
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mkt-senha
      - ME_CONFIG_MONGODB_SERVER=mongo-mkt

volumes:
  data: {}

networks:
  default:
    name: mongodb_network


