version: '3.7'
services:
  web-mkt:
    image: java
    container_name: web-mkt
    volumes:
      - ./:/app
    working_dir: /app
    command: ./mvnw package
    environment:
      SERVER_PORT: 8085
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo-mkt
  mongo-mkt:
    image: mongo
    container_name: mongo-mkt
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mkt-usuario
      MONGO_INITDB_ROOT_PASSWORD: mkt-senha
      MONGO_INITDB_DATABASE: mkt
  rabbitmq:
    container_name: rabbitmq-mkt
    image: rabbitmq
    ports:
      - 5672:5672
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mkt-usuario
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mkt-senha
      - ME_CONFIG_MONGODB_SERVER=mongo-mkt

volumes:
  data: {}

networks:
  default:
    name: mongodb_network


