server:
  port: 0
spring:
  data:
    mongodb:
      database: mongo-mkt
      port: 27017
      host: ${MONGO_DATABASE_HOST:localhost}
      authentication-database: admin
      username: mkt-usuario
      password: mkt-senha
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    password: admin
    username: admin
  application:
    name: marketing
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka