server:
  port: 8086
spring:
  data:
    mongodb:
      database: mongo-mkt
      port: 27017
      host: mongo-mkt
      authentication-database: admin
      username: mkt-usuario
      password: mkt-senha
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: admin
    username: admin